version: "3.9"

services: 
  frontend:
    build: ./frontend
    image: "misterpea/aws:frontend"
    depends_on: 
      - backend
    networks: 
      - nyt-net
  
  backend:
    build: ./backend
    image: "misterpea/aws:backend"
    networks: 
      - nyt-net
  
  revproxy:
    build: ./nginx
    depends_on: 
      - frontend
      - backend
    image: "misterpea/aws:reverseproxy"
    networks: 
      - nyt-net
    ports: 
      - "80:80"
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

networks: 
  nyt-net: