version: '3.7'

services:
  backend:
    # env_file: 
    #   "./backend/.env"
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: "production-nytimes-backend"
    ports: 
      - "8090:8090"
  frontend:
    image: "production-nytimes-frontend"
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports: 
      - "8080:8080"
    