name: Deploy to GCP Compute Engine

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GCP Compute Engine
    runs-on: ubuntu-latest

    steps:
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: Setup gcloud SDK
      uses: google-github-actions/setup-gcloud@v0
    
    - name: Clone Repository
      run: |
        gcloud compute ssh nyt-aggregator-instance-group-60v5 --zone=us-east4-c --command="sudo rm -r NYTimes-Aggregator"
        gcloud compute ssh nyt-aggregator-instance-group-60v5 --zone=us-east4-c --command="git clone https://github.com/MisterPea/NYTimes-Aggregator.git"
    
    - name: Remove previous docker files
      run: |
        gcloud compute ssh nyt-aggregator-instance-group-60v5 --zone=us-east4-c --command="cd NYTimes-Aggregator && docker-compose down"
        gcloud compute ssh nyt-aggregator-instance-group-60v5 --zone=us-east4-c --command="sudo docker image prune -a --force"
        
    - name: Run docker-compose - detached
      run: gcloud compute ssh nyt-aggregator-instance-group-60v5 --zone=us-east4-c --command="cd NYTimes-Aggregator && sudo docker-compose up -d"
